### ISSUE TITLE
Where does the official purl test suite come from?

### ISSUE THREAD

**Issue by sjn** [giterlizzi/perl-URI-PackageURL#11]
Hei!

`t/99-official-purl-test-suite.t` is great to have, but needs a link to where the original data is from, so it's possible to keep it in sync as the original gets updated.

Also, with the upcoming versioning support, and Philippe's ambitions of formalizing the standard, knowing of - and using - authoritative test data is extra useful.

Maybe add a link, at minimum, and consider adding some way of keeping test data in sync with upstream?

**Comment by giterlizzi** [comment]
A great idea.

I modified `t/99-official-purl-test-suite.t` to read the original JSON file instead of having it embedded (in `__DATA__`), so as not to modify the file when Philippe adds or modifies tests.

I also added a shell script for downloading tests from the "purl" spec repository (https://raw.githubusercontent.com/package-url/purl-spec/master/test-suite-data.json), to make it easier to update the file offline or from CI/CD.
